## Geophysical Data Analysis: Discrete Inverse Theory
### William Menke
Third Edition  
Transcribed and translated (from Matlab to Python) by Joshua Poirier

## Chapter One
# Describing Inverse Theory

### 1.1 Formulating inverse problems
The starting place in most inverse problems is a description of the data.  Since in most inverse problems the data are simply a list of numerical values, a vector provides a convenient means of their representation.  If *N* measurements are performed in a particular experiment, for instance, one might consider these numbers as the elements of a vector **d** of length *N*.  

The purpose of data analysis is to gain *knowledge* through systematic examination of data.  While knowledge can take many forms, we assume here that it is primarily numerical in nature.  We analyze data so to infer, as best we can, the values of numerical quantities - *model parameters*.  Model parameters are chosen to be *meaningful*; that is, they are chosen to capture the essential character of the processes that are being studied.  The model parameters can be represented as the elements of a vector **m**, which is of length *M*.

\begin{equation*}
\text{data:} \mathbf{d} = \begin{bmatrix}d_1 & d_2 & d_3 & \cdots & d_N \end{bmatrix}^T \\
\text{model parameters:} \mathbf{m} = \begin{bmatrix}m_1 & m_2 & m_3 & \cdots & m_M \end{bmatrix}^T
\end{equation*}

The basic statement of an inverse problem is that the model parameters and the data are in some way related.  This relationship is called the *quantitative model*.  Usually, the model takes the form of one or more formulas that the data and model parameters are expected to follow.  
In realistic situations, the data and model parameters are related in complicated ways.  Most generally, the data and model parameters might be related by one or more implicit equations such as:

\begin{equation*}
\begin{matrix}
f_1(\mathbf{d}, \mathbf{m}) = 0 \\
f_2(\mathbf{d}, \mathbf{m}) = 0 \\
\vdots \\
f_L(\mathbf{d}, \mathbf{m}) = 0
\end{matrix}
\qquad \text{or} \qquad \mathbf{f}(\mathbf{d}, \mathbf{m}) = 0
\end{equation*}

Where *L* is the number of equations.  These impliicit equations, which can be compactly written as the vector equation **f**(**d**, **m**) = 0, summarize what is known about how the measured data and the unknown model parameters are related.  The purpose of inverse theory is to solve, or "invert," these equations for the model parameters, or whatever kinds of answers might be possible or desirable in any given situation.  

No claims are made either that the equations contain enough information to specify the model parameters uniquely or that they are even consistent.  One of the purposes of inverse theory is to answer these kinds of questions and provide means of dealing with the problems that they imply.  In general, **f**(**d**, **m**) = 0 can consist of arbitrarily complicated (nonlinear) functions of the data and model parameters.  In many problems, however, the equation takes on one of several simple forms.  It is convenient to give names to some of these special cases, since they commonly arise in practical problems; we shall give them special consideration in later chapters.  

#### 1.1.1 Implicit linear form
The function **f** is linear in both data and model parameters and can therefore be written as the matrix equation:

\begin{equation*}
\mathbf{f}(\mathbf{d}, \mathbf{m}) = 0 = \mathbf{F} \begin{bmatrix} \mathbf{d} \\ \mathbf{m} \end{bmatrix} = \mathbf{Fx}
\end{equation*}

Where **F** is an $L \times (M+N)$ matrix and the vector **x** = $[\mathbf{d}^T, \mathbf{m}^T]^T$ is a concatenation of **d** and **m**, that is, **x** = $\begin{bmatrix}d_1 & d_2 & \cdots & d_N & m_1 & m_2 & \cdots & m_M \end{bmatrix}^T$.

#### 1.1.2 Explicit form
In many instances, it is possible to separate the data from the model parameters and thus to form *L=N* equations that are linear in the data (but still nonlinear in the model parameters through the vector function **g**).

\begin{equation*}
\mathbf{f}(\mathbf{d}, \mathbf{m}) = 0 = \mathbf{d} - \mathbf{g}(\mathbf{m})
\end{equation*}

#### 1.1.3 Explicit linear form
In the explicit linear form, the function **g** is also linear, leading to the *NxM* matrix equation (where *L=N*).

\begin{equation*}
\mathbf{f}(\mathbf{d}, \mathbf{m}) = 0 = \mathbf{d} - \mathbf{Gm}
\end{equation*}

This form is equivalent to a special case of the matrix **F** in Section **1.1.1**:

\begin{equation*}
\mathbf{F} = [\mathbf{I}, - \mathbf{G}]
\end{equation*}

### 1.2 The linear inverse problem
The simplest and best-understood problems are those that can be represented with the explicit linear equation **Gm** = **d**.  This equation, therefore, forms the foundation of the study of discrete inverse theory.  As will be shown below, many important inverse problems that arise in the physical sciences involve precisely this equation.  Others, while involving more complicated equations, can often be solved through linear approximations.  

The matrix **G** is called the data kernel, in analogy to the theory of integral equations, in which the analogs of the data and model parameters are two continuous functions *d(x)* and *m(x)*, where *x* is some independent variable.  Continuous inverse theory lies between these two extremes, with discrete data but a continuous model function.

\begin{equation*}
\text{Discrete inverse theory}
\qquad
d_i = \sum_{j=1}^M G_{i,j} m_j
\\
\text{Continuous inverse theory}
\qquad
d_i = \int G_i(x) m(x) dx
\\
\text{Integral equation theory}
\qquad
d(y) = \int G(y,x) m(x) dx
\end{equation*}

The main difference among discrete inverse theory, continuous inverse theory, and integral equation theory is whether the model *m* and data *d* are treated as continuous functions or discrete parameters.  The data $d_i$ in inverse theory are necessarily discrete, since inverse theory is concerned with deducing knowledge from observational data, which always has a discrete nature.  Both continuous inverse problems and integral equations can be converted to discrete inverse problems by approximating the model *m(x)* as a vector of its values at a set of *M* closely spaced points.

\begin{equation*}
\mathbf{m} = \begin{bmatrix} m(x_1) & m(x_2) & \cdots & m(x_M) \end{bmatrix}^T
\end{equation*}

And the integral as a Riemann summation (or by some other quadrature formula).

### 1.3 Examples of formulating inverse problems
#### 1.3.1 Example 1: Fitting a straight line
Suppose that *N* temperature measurements $T_i$ are made at times $t_i$ in the atmosphere.  The data are then a vector **d** of *N* measurements of temperature, where $\mathbf{d} = \begin{bmatrix} T_1 & T_2 & \cdots & T_N \end{bmatrix}^T$.  The times $t_i$ are not, strictly speaking, data.  Instead, they provide some auxiliary information that describes the geometry of the experiment.  

Suppose that we assume a model in which temperature is a linear function of time: $T = a + bt$.  The intercept *a* and slope *b* then form the two model parameters of the problem, $\mathbf{m} = [a, b]^T$.  According to the model, each temperature observation must satisfy $T_i = a + bt_i$:

\begin{equation*}
T_1 = a + bt_1 \\
T_2 = a + bt_2 \\
\vdots \\
T_N = a + bt_N
\end{equation*}

These equations can be arranged as the matrix equation **d** = **Gm**.

\begin{equation*}
\begin{bmatrix} T_1 \\ T_2 \\ \vdots \\ T_N \end{bmatrix} =
\begin{bmatrix} 1 & t_1 \\ 1 & t_2 \\ \vdots & \vdots \\ 1 & t_N \end{bmatrix}
\begin{bmatrix} a \\ b \end{bmatrix}
\end{equation*}

In *Python*, we can build the vector **d** and matrix **G** by:

In [1]:
import pandas as pd
import numpy as np

# read data file to dataframe
df = pd.read_csv("../data/global_temp.txt", delim_whitespace=True, header=None, names=["Year", "TempChange"])

# get number of rows in data frame
n = df.shape[0]

# extract dependent data (temp change) and independent data (year) from dataframe into appropriate vector d and matrix G
d = df.as_matrix(columns=["TempChange"])
G = np.ones((n, 2))
G[:, 1] = df.as_matrix(columns=["Year"])[:,0]

print("d = ")
print(d[0:4])
print("")
print("G =")
print(G[0:4,:])

d = 
[[-0.11]
 [-0.03]
 [-0.01]
 [-0.04]]

G =
[[  1.00000000e+00   1.96500000e+03]
 [  1.00000000e+00   1.96600000e+03]
 [  1.00000000e+00   1.96700000e+03]
 [  1.00000000e+00   1.96800000e+03]]


#### 1.3.2 Example 2: Fitting a parabola
If the model in Example 1 is changed to assume a quadratic variation of temperature with time of the form $T = a + bt + ct^2$, then a new model parameter *c* is added to the problem, and $\mathbf{m} = [a, b, c]^T$.  The number of model parameters is now *M=3*.  The data and model parameters are supposed to satisfy:  

\begin{equation*}
T_1 = a + bt_1 + ct_1^2 \\
T_2 = a + bt_2 + ct_2^2 \\
\vdots \\
T_N = a + bt_N + ct_N^2
\end{equation*}

These equations can be arranged into the matrix equation:  

\begin{equation*}
\begin{bmatrix} T_1 \\ T_2 \\ \vdots \\ T_N \end{bmatrix} =
\begin{bmatrix} 1 & t_1 & t_1^2 \\ 1 & t_2 & t_2^2 \\ \vdots & \vdots & \vdots \\ 1 & t_N & t_N^2 \end{bmatrix}
\begin{bmatrix} a \\ b \\ c \end{bmatrix}
\end{equation*}

This matrix equation has the explicit linear form **d** = **Gm**.  Note that, although the equation is linear in the data and model parameters, it is not linear in the auxiliary variable *t*.  

The equation has a very similar form to the equation of the previous example, which brings out one of hte underlying reasons for employing matrix notation: it can often emphasize similarieties between superficially different problems.  In *Python*, we can compute this new **G** matrix by:

In [20]:
# initialize new matrix G
G = np.ones((n,3))

# extract independent data (year) from data frame
t = df.as_matrix(columns=["Year"])[:,0]

# insert independent data (and it's element-wise square) into the matrix G
G[:, 1] = t
G[:, 2] = np.multiply(t, t)

print(G[0:4, :])

[[  1.00000000e+00   1.96500000e+03   3.86122500e+06]
 [  1.00000000e+00   1.96600000e+03   3.86515600e+06]
 [  1.00000000e+00   1.96700000e+03   3.86908900e+06]
 [  1.00000000e+00   1.96800000e+03   3.87302400e+06]]


#### 1.3.3 Example 3: Acoustic tomography
Suppose that a wall is assembled from a rectangular array of bricks and that each brick is composed of a different type of clay.  If the acoustic velocities of the different clays differ, one might attempt to distinguish the different kinds of bricks by measuring hte travel time of sound across the various rows and columns of bricks in the wall.  The data in this problem are *N=8* measurements of travel times, $d = [T_1, T_2, \cdots, T_8]^T$.  The model assumes that each brick is composed of a uniform material and that the travel time of sound across each brick is proportional to the width and height of the brick.  The proporitionality factor is the brick's *slowness* $s_i$, thus giving *M=16* model parameters $\mathbf{m} = [s_1, s_2, \cdots, s_{16}]^T$, where the ordering is according to the numbering scheme of the figure.  The data and model parameters are related by:  

\begin{equation*}
\begin{matrix}
\text{row 1: }T_1 = hs_1 + hs_2 + hs_3 + hs_4 \\
\text{row 2: }T_1 = hs_5 + hs_6 + hs_7 + hs_8 \\
\vdots \\
\text{column 4: }T_1 = hs_4 + hs_8 + hs_{12} + hs_{16} \\
\end{matrix}
\end{equation*}

And the matrix equation is:

\begin{equation*}
\begin{bmatrix} T_1 \\ T_2 \\ \vdots \\ T_8 \end{bmatrix} = h
\begin{bmatrix}
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
s_1 \\ s_2 \\ \vdots \\ s_{16}
\end{bmatrix}
\end{equation*}

If we assume the bricks to be of width *and* height *h*, then the *Python* code for building the matrix **G** is:

In [25]:
G = np.zeros((8, 16))

# loop through rows
for i in range(0, 4):
    # loop through columns
    for j in range(0, 4):
        # row measurements
        k = i * 4 + j
        G[i, k] = 1
        
        # column measurements
        k = j * 4 + i
        G[i + 4, k] = 1
        
print(G)

[[ 1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.]]


#### 1.3.4 Example 4: X-ray imaging
Tomography is the process of forming images of the interior of an object from measurements made along rays passed through that object ("tomo" comes from the Greek word for "slice").  The computerized tomography scanner is an X-ray imaging device that has revolutionized the diagnosis of brain tumors and many other medical conditions.  The scanner solves an inverse problem for the X-ray opacity of body tissues using measurements of the amount of radiation absorbed from many crisscrossing beams of X-rays.  

The basic physical model underlying this device is the idea that the intensity of X-rays diminishes with the distance traveled, at a rate proportional to the intensity of the X-ray beam, and an absorption coefficient that depends on the type of tissue.  

\begin{equation*} \frac{dI}{ds} = -c(x,y)I \end{equation*}  

Here, *I* is the intensity of the beam, *s* the distance along the beam, and *c(x,y)* the absorption coefficient, which varies with position.  If the X-ray source has intensity $I_0$, then the intensity at the *i*th detector is:

\begin{equation*}
I_i = I_0 \text{exp} \lbrace - \int_{\text{beam}i} c(x,y) ds \rbrace \approx I_0 \lbrace 1 - \int_{\text{beam}i} c(x,y) ds \rbrace \\
I_0 - I_i = I_0 \int_{\text{beam}i} c(x,y) ds
\end{equation*}

Note that the equation above is a nonlinear function of the unknown absorption coefficient *c(x,y)* and that the absorption coefficient varies continuously along the beam.  This is a nonlinear problem in continuous inverse theory.  However, it can be linearized, for small net absorption, by approximating the exponential with the first two terms in its Taylor series expansion, that is, exp(*-x*) $\approx$ 1 - *x*.  

We now convert this problem to a discrete inverse problem of the form **Gm** = **d**.  We assume that the continuously varying absorption coefficient can be adequately represented by a grid of many small square boxes (or *pixels*), each of which has a constant absorption coefficient.  With these pixels numbered 1 through *M*, the model parameters are then the vector **m** = $[c_1, c_2, \cdots, c_M]^T$.  The integral can then be written as the sum:  

\begin{equation*}
\Delta I_i = \frac{I_0 - I_i}{I_0} = \sum_{j=1}^{M} \Delta s_{i,j} c_j
\end{equation*}

Here, the data $d_i = \Delta I_i$, represent the differences between the X-ray intensities at the source and at the detector, and $G_{i,j} = \Delta s_{i,j}$ is the distance the *i*th beam travels in the *j*th pixel.  

The inverse problem can then be summarized by the matrix equation:  

\begin{equation*}
\begin{bmatrix}  \Delta I_1 \\ \Delta I_2 \\ \vdots \\ \Delta I_N \end{bmatrix} =
\begin{bmatrix}
\Delta s_{1,1} & \Delta s_{1,2} & \cdots & \Delta s_{1,M} \\
\Delta s_{2,1} & \Delta s_{2,2} & \cdots & \Delta s_{2,M} \\
\vdots & \vdots & \ddots & \vdots \\
\Delta s_{N,1} & \Delta s_{N,2} & \cdots & \Delta s_{N,M}
\end{bmatrix}
\begin{bmatrix}  c_1 \\ c_2 \\ \vdots \\ c_M \end{bmatrix}
\end{equation*}

Since each beam passes through only a few of the many boxes, many of the $\Delta s_{i,j}$ are zero.  Such a matrix is said to be *sparse*.  

Computations with sparse matrices can be made extremely efficient by storing only the nonzero elements and by never explicitly multiplying or adding the zero elements (since the result is a foregone conclusion).  However, special software support is necessary to gain this efficiency, since the computer must keep track of the zero elements.  In *Python*, the **CSR** format from the *SciPy* package is specially suited for fast matrix vector products.  

In [27]:
from scipy.sparse import csr_matrix

# build a sparse matrix A, and vector v
A = csr_matrix([[1,2,0], [0,0,3], [4,0,5]])
v = np.array([1, 0, -1])

# multiply and output sparse matrix A and vector v
A.dot(v)

array([ 1, -3, -1], dtype=int32)

#### 1.3.5 Example 5: Spectral curve fitting
Not every inverse problem can be adequately represented by the discrete linear equation **Gm** = **d**.  Consider, for example, a spectrogram containing a set of emission or absorption peaks, that vary with some auxiliary variable *z*.  The positions *f*, area *A*, and width *c* of the peaks are of interest because they reflect the chemical composition of the sample.  Denoting the shape of the peak *j* as $p(z_i, f_j, A_j, c_j)$ is taken to be a *Lorentzian*.  The data and model are therefore related by the *nonlinear* explicit equation **d** = **g**(**m**), where **m** is a vector of the position, area, and width of each peak.  This equation is inherently nonlinear.  

#### 1.3.6 Example 6: Factor analysis
Another example of a nonlinear inverse problem is that of determining the composition of chemical end members on the basis of the chemistry of a suiute of mixtures of the end members.  Consider a simplified "ocean" in which sediments are composed of mixtures of several chemically distinct rocks eroded from the continents.  One expects the fraction of chemical *j* in the *i*th sediment sample $S_{i,j}$ to be related to the amount of end-member rock in sediment sample $i(C_{i,k})$ and to the amount of the *j*th chemical in the end-member rock ($F_{k,j}$) as:  

\begin{equation*}
\begin{bmatrix} sample \\ composition \end{bmatrix} =
\sum_{end members} 
\begin{bmatrix} \text{amount of} \\ \text{end member} \end{bmatrix}
\begin{bmatrix} \text{end member} \\ \text{composition} \end{bmatrix} \\
S_{i,j} = \sum_{k=1}^p C_{i,k} F_{k,j}
\qquad \text{or} \qquad \mathbf{S} = \mathbf{CF}
\end{equation*}

In a typical experiment, the number of end members *p*, the end-member composition **F**, and the amount of end members in the samples **C** are all unknown model parameters.  Since the data **S** are on one side of the equations, this problem is also of the explicit nonlinear type.  Note that basically the problem is to factor a matrix **S** into two other matrices **C** and **F**.  This factoring problem is a well-studied part of the theory of matrices, and methods are available to solve it.  